image: python:3.9.15

before_script:
  - python --version
  - cd areas/backend
  - pip install -r requirements.txt

stages:
  - Test

pytest:
  stage: Test
  script:
  - python3 -m pytest ./tests/test_cc
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'