# This workflow will install Python dependencies, and run tests with a single version of Python

name: pytest

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  test_core:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-xdist
    - name: Core tests
      working-directory: areas/backend
      run: python3 -m pytest -n auto ./tests/test_core

  test_api:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        working-directory: areas/backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: API tests
        working-directory: areas/backend
        run: python3 -m pytest -n auto ./tests/test_new_api

  test_ui:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          docker-compose -p data_manage_system up --build -d
          docker ps -a

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        working-directory: areas/backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: UI tests
        working-directory: areas/backend
        run: python3 -m pytest --headless --debug_log ./tests/test_ui
      - name: Archive tests logs
        uses: actions/upload-artifact@v3
        with:
          name: test_logs
          path: areas/backend/tmp/test.log